version: '3.8'

services:
  db:
    image: postgres:17
    container_name: task_manager_db
    environment:
      POSTGRES_DB: task_manager_db
      POSTGRES_USER: task_manager_user
      POSTGRES_PASSWORD: task_manager_password
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: task-manager-service
    container_name: task_manager_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/task_manager_db
      SPRING_DATASOURCE_USERNAME: task_manager_user
      SPRING_DATASOURCE_PASSWORD: task_manager_password
    depends_on:
      - db

volumes:
  postgres_data: